/*/{Protheus.doc} qiea270SX
Abre a tabela de Fatores I.A. na interface SmartX.
@type function
@author willian.ramalho
@since 25/08/2026
@return variant, resultado da abertura da interface
/*/
Function qiea270SX()

    local lCompVer  := GetRPORelease() >= "12.1.2610"
    local oLauncher := Nil

    If !lCompVer
        Return Nil
    EndIf

    oLauncher := launcher():new()
    oLauncher:setInterface("totvs.protheus.manufacturing.incominginspection.QualityFactorsIAInterface")

Return oLauncher:open()
