/*/{Protheus.doc} QualityFactorsIAInterface
Interface SmartX da tabela de Fatores I.A. (QEJ, QEJ_CODTAB="1").
@type class
@author willian.ramalho
@since 25/08/2026
/*/
@totvsFrameworkStructureInterface(description="Fatores I.A.")
class QualityFactorsIAInterface
    private data oInterface as object
    public method new() as object
    public method setInterface()
    public method getContract() as json
endclass
